services:
  dotg-booking:
    container_name: dotg-booking
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5051:5051
    restart: on-failure